
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "CONJUNCTION DISJUNCTION IMPLICATION VARformular : var\n               | disjunctive_formular\n               | conjunctive_formular\n               | implicative_formular\n               | negative_formular\n               | '(' formular ')'\n                var : VAR \n    disjunctive_formular : '(' formular DISJUNCTION formular ')'\n                         |  formular DISJUNCTION formular \n    \n    conjunctive_formular : '(' formular CONJUNCTION formular ')'\n                         |  formular CONJUNCTION formular \n    \n    implicative_formular : '(' formular IMPLICATION formular ')'\n                         |  formular IMPLICATION formular\n    \n    negative_formular : '~' '(' formular ')'\n                      | '~' formular \n    "
    
_lr_action_items = {'(':([0,7,9,10,11,12,14,20,21,22,],[7,7,14,7,7,7,7,7,7,7,]),'VAR':([0,7,9,10,11,12,14,20,21,22,],[8,8,8,8,8,8,8,8,8,8,]),'~':([0,7,9,10,11,12,14,20,21,22,],[9,9,9,9,9,9,9,9,9,9,]),'$end':([1,2,3,4,5,6,8,15,16,17,18,19,27,28,29,30,],[0,-1,-2,-3,-4,-5,-7,-15,-9,-11,-13,-6,-6,-8,-10,-12,]),'DISJUNCTION':([1,2,3,4,5,6,8,13,15,16,17,18,19,23,24,25,26,27,28,29,30,],[10,-1,-2,-3,-4,-5,-7,20,10,10,10,10,-6,20,10,10,10,-6,-8,-10,-12,]),'CONJUNCTION':([1,2,3,4,5,6,8,13,15,16,17,18,19,23,24,25,26,27,28,29,30,],[11,-1,-2,-3,-4,-5,-7,21,11,11,11,11,-6,21,11,11,11,-6,-8,-10,-12,]),'IMPLICATION':([1,2,3,4,5,6,8,13,15,16,17,18,19,23,24,25,26,27,28,29,30,],[12,-1,-2,-3,-4,-5,-7,22,12,12,12,12,-6,22,12,12,12,-6,-8,-10,-12,]),')':([2,3,4,5,6,8,13,15,16,17,18,19,23,24,25,26,27,28,29,30,],[-1,-2,-3,-4,-5,-7,19,-15,-9,-11,-13,-6,27,28,29,30,-6,-8,-10,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formular':([0,7,9,10,11,12,14,20,21,22,],[1,13,15,16,17,18,23,24,25,26,]),'var':([0,7,9,10,11,12,14,20,21,22,],[2,2,2,2,2,2,2,2,2,2,]),'disjunctive_formular':([0,7,9,10,11,12,14,20,21,22,],[3,3,3,3,3,3,3,3,3,3,]),'conjunctive_formular':([0,7,9,10,11,12,14,20,21,22,],[4,4,4,4,4,4,4,4,4,4,]),'implicative_formular':([0,7,9,10,11,12,14,20,21,22,],[5,5,5,5,5,5,5,5,5,5,]),'negative_formular':([0,7,9,10,11,12,14,20,21,22,],[6,6,6,6,6,6,6,6,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formular","S'",1,None,None,None),
  ('formular -> var','formular',1,'p_formular','bool.py',33),
  ('formular -> disjunctive_formular','formular',1,'p_formular','bool.py',34),
  ('formular -> conjunctive_formular','formular',1,'p_formular','bool.py',35),
  ('formular -> implicative_formular','formular',1,'p_formular','bool.py',36),
  ('formular -> negative_formular','formular',1,'p_formular','bool.py',37),
  ('formular -> ( formular )','formular',3,'p_formular','bool.py',38),
  ('var -> VAR','var',1,'p_var','bool.py',45),
  ('disjunctive_formular -> ( formular DISJUNCTION formular )','disjunctive_formular',5,'p_disjunctive_formular','bool.py',51),
  ('disjunctive_formular -> formular DISJUNCTION formular','disjunctive_formular',3,'p_disjunctive_formular','bool.py',52),
  ('conjunctive_formular -> ( formular CONJUNCTION formular )','conjunctive_formular',5,'p_conjunctive_formular','bool.py',59),
  ('conjunctive_formular -> formular CONJUNCTION formular','conjunctive_formular',3,'p_conjunctive_formular','bool.py',60),
  ('implicative_formular -> ( formular IMPLICATION formular )','implicative_formular',5,'p_implicative_formular','bool.py',67),
  ('implicative_formular -> formular IMPLICATION formular','implicative_formular',3,'p_implicative_formular','bool.py',68),
  ('negative_formular -> ~ ( formular )','negative_formular',4,'p_negative_formular','bool.py',75),
  ('negative_formular -> ~ formular','negative_formular',2,'p_negative_formular','bool.py',76),
]
